### ISSUE TITLE
connect gives error 

### ISSUE THREAD

**Issue by derrgis** [256dpi/max-mqtt#2]
Trying to get it working under Max 7.3.5 32bits - Mac OSX.11.6
Legacy Java for OSX is well installed and the [mxj mqtt] object is instancied but I'm not able to have the connexion to mqtt://shiftr-io:try@connect.shiftr.io nor my own mosquitto broker in localhost.

Max error:
java.lang.ExceptionInInitializerError
	at org.eclipse.paho.client.mqttv3.MqttClient.<init>(MqttClient.java:224)
	at mqtt.connect(mqtt.java:68)
Caused by: java.util.MissingResourceException: Can't find bundle for base name org.eclipse.paho.client.mqttv3.internal.nls.logcat, locale fr_FR
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1427)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1250)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:705)
	at org.eclipse.paho.client.mqttv3.logging.LoggerFactory.getLogger(LoggerFactory.java:73)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<clinit>(MqttAsyncClient.java:79)

Any help would be appreciated.
Also I'm a newbie ...

**Comment by 256dpi** [comment]
The documentation referenced the old shiftr.io URL "mqtt://shiftr-io:try@connect.shiftr.io". It has been changed to "mqtt://try:try@broker.shiftr.io" some time ago.
